apiVersion: appls/v1
kind: Deployment
metadata:
  name: docktest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docktest
  template:
    metadata:
      labels:
        app: docktest
    spec:
      containers: 
        - name: docktest
          image: dhruvrs/baseapp:latest
          ports: 
            - containerPort: 8000